F/Face Recognition using OpenCV/README.md, F/Face Recognition using OpenCV/main.py
This is A Face Recognition Project developed using OpenCV Module in Python. This Display a Blue Reactangle Frame around Faces.
=> Face Recognition Project developed using OpenCV Module in Python.

E/email-sender/email_sender.py
- refact send email
- pass username, password and subject via args
=> send email with functions

A/automate-login/automate_login.py
- Refact automate login structure
- Pass credentials via args
=> chore: refact automate login and pass credentials via bash

G/gradient_descent_for_machine_learning/gradient_descent.py
I have created a new gradient descent from scratch algorithm for linear regression implementation from scratch. Please accept my pull request it would be my first contribution to any open source project, if everything is fine. Thank You. Have a nice day.
=> gradient descent dir created

R/random-player-elimination-game/README.md, R/random-player-elimination-game/random-player-elimination-game.py
This pull request introduces a new Python project inside the 'R' directory called "Random Player Elimination Game." The game is designed to provide a simple, entertaining experience where players are randomly eliminated until only one player remains as the winner.
1. Added a new directory inside 'R' directory called 'random-player-elimination-game' inside which is a README.md file and Python script (`random-player-elimination-game.py`) containing the game logic.
2. Created a README.md file with detailed instructions on how to play the game and set it up.
=> Random Player Elimination Game

J/README.md, J/joke_generator.py, J/requirements.txt
Always have a joke up your sleeve!
=> Cool Jokes

E/encrypt-pdf/encrypt_pdf.py
1. Added descriptive comments throughout the code to clarify the purpose of functions and code blocks.
2. Improved variable names to make the code more self-explanatory.
3. Enhanced error handling by providing more informative error messages.
4. Simplified code sections for conciseness and better readability.
5. Reorganized the code for improved structure and readability.
6. Ensured adherence to PEP 8 style guidelines for code consistency.
These improvements make the PDF encryption and decryption script easier to understand, use, and maintain.
=> Refactor PDF Encryption and Decryption Script

T/type-speed-tester/README.md
This is my very first pull request to an open source project, so I'm not sure how really to help out so I just wrote a quick description of one of the projects. If there's anything I'm doing wrong at all please let me know, git is a bit overwhelming right now haha. I basically used vscode to clone the repo and then from there commit and push it as well, before creating the pull request on the github website.
=> Adding a description of the program to the README

C/convert-rgb-to-hex/README.md, C/convert-rgb-to-hex/convert-rgb-to-hex.py
I've added two functions for converting between HEX and RGB color representations. The `hex_to_rgb` function converts a HEX color code to its RGB components, while the `rgb_to_hex` function does the reverse.
- Added `hex_to_rgb` function.
- Added `rgb_to_hex` function.
```python
print(rgb_to_hex(0, 0, 0))         # Output: #000000
print(rgb_to_hex(34, 139, 34))     # Output: #228B22
print(rgb_to_hex(0, 128, 255))     # Output: #0080FF
print(rgb_to_hex(255, 255, 0))     # Output: #FFFF00
print(rgb_to_hex(255, 0, 128))     # Output: #FF0080
```
```python
print(hex_to_rgb("#000000"))       # Output: (r: 0, g: 0, b: 0)
print(hex_to_rgb("#228B22"))       # Output: (r: 34, g: 139, b: 34)
print(hex_to_rgb("#0080FF"))       # Output: (r: 0, g: 128, b: 255)
print(hex_to_rgb("#FFFF00"))       # …
```
=> Create rgb-hex convert

T/timer/README.md, T/timer/timer.py
A basic Python program that allows you to set a timer for a specified duration and counts down to notify you when the time is up.
=> Simple Timer Program

R/rock paper scissors/README.md, R/rock paper scissors/main.py
CLI-based rock, paper, scissor game
=> Add rock paper scissors

BarGraph.py, KBC Game.py
=> Created KBC Game.py

armstrong.py
Hello ,
I have tried to improvise the Armstrong number code , it would be helpful if anyone can review it .
Thanks in Advance
Priyanshu Jha (pjha8040)
=> added 4 digit checker

P/Personal-Budget-manager/tkt.py
I have made a GUI tkinter python budget manager under Hacktoberfest.
=> A Personal Budget manager using Tkinter.

B/BlackJack_cardgame/game.py, B/BlackJack_cardgame/readme.txt
I have created this classic BlackJack card game . This game does not require any extra python packages and is built on basic python programming ! Hope you merge this code into your main branch.
=> Added classic BlackJack card game

S/Sudoku Solver/.gitignore, S/Sudoku Solver/GUI.py, S/Sudoku Solver/readme.md, S/Sudoku Solver/solver.py
I have added soduku solver project.
Please add me as assignee and add hacktoberfest and hacktoberfest-accepted label and please merge this pr
Thank you.
=> Soduku Solver Project [hacktoberfest]

S/Sort the list according to the column using lambda
Given a list, the task is to sort the list according to the column using the lambda approach
=> Create Sort the list according to the column using lambda

A/AutoPC_LockUnlock/lock_unlock.py, A/AutoPC_LockUnlock/readme.txt
I have created a code to feature a automation of the lock and unlock of the PC.
Please add me as assignee and add hacktoberfest and hacktoberfest-accepted label and please merge this pr
Thank you.
=> (FEATURE): Automate PC Lock And Unlock by the Detection of Presence or Absence of a Person

D/Discord Jokes Bot/bot.py
Please add the Hacktoberfest tag
=> Added Discord Bot which tells jokes - Hacktoberfest

palindrome.py
hello,
I have added a new program that checks , if the string / number is a palindrome or not .
Regards
Priyanshu Jha ( pjha8040 )
=> palindrome number/string checker

B/Random Binary Tree Generator/treegenerator.py, P/Palindrome/palindrome_number.py, P/Palindrome/palindrome_string.py
Greetings,
The programs I am submitting checks whether the input String/number is palindrome or not
Hoping for a favorable reply,
Arnavthakare19
=> Added palindrome folder

P/Py-game-boilerplate-setup/py-game-boilerplatesetup.py
Please review this boilerplate program of Py-game for ease of usage of developers. Hope this request gets merged. Thank You, have a nice day.
=> Boilerplate pygame file has been created

A/Atm banking system/Atm.py, A/Atm banking system/README.md
Atm banking system using python has been implemented. OOP concepts were used in this project.
Pleaser add hacktober fest label.
=> Atm banking system using python OOP concepts

L/library-management-system/main.py, L/library-management-system/readme.md
This code provides a basic structure for a library management system with functions to add books, remove books, list books, add users, borrow books, return books, and list users.
=> Added Library Management System Code

C/chatgpt-based-voice-assistant/README.md, C/chatgpt-based-voice-assistant/requirements.txt, C/chatgpt-based-voice-assistant/voice-assistant.py, README.md
Added a ChatGPT based voice assistant to help with your queries.
=> Create a ChatGPT based voice assistant

W/word guessing game
we will use the random module to make a word-guessing game. This game is for beginners learning to code in python and to give them a little brief about using strings, loops, and conditional(If, else) statements.
=> Create word guessing game

W/whatsapp birthday bot
Have you ever wished to automatically wish your friends on their birthdays, or send a set of messages to your friend ( or any Whastapp contact! ) automatically at a pre-set time, or send your friends by sending thousands of random text on whatsapp! Using Browser Automation you can do all of it and much more!
=> Create whatsapp birthday bot

N/notes-app/README.md, N/notes-app/functions.py, N/notes-app/notes-app.py
**Pull Request Title:** Add Notes App - A Command-Line Note Management Tool
**Description:**
This pull request adds a new Python application called the "Notes App." It is a command-line tool designed to help users create, view, and delete text-based notes with ease. Here are the key features and changes included in this PR:
- **Notes App Features:**
- Create new notes with titles and content.
- View the contents of existing notes.
- Delete notes when they are no longer needed.
- User-friendly command-line interface.
- **Project Structure:**
- Added a new `notes-app.py` file containing the Notes App inside N directory.
- Separated functionality into a `functions.py` module for improved code organization.
- **README.md Update:**
- Included detailed instructions on how to install, run, and …
=> Added notes app

M/MergeSort.py, M/Message-Spam/README.md, M/Message-Spam/mesaage_spam.py, M/Message-Spam/requirements.txt
1. Added a Message Spam script
2. Added Merge Sort
=> Added a new project Message Spam and MergeSort

C/Cover-STEG/README.md, C/Cover-STEG/app.py
Hiding a Secret Text in a plain sight
ZWSP based tool used in steganography
=> Cover python based steganography tool 

T/traveling-salesman-problem/tsp.py
a code to compare the time complexity of traveling salesman problem in 
- dynamic programming 
- greedy algo 
- brute force algo
=> traveling salesman problem

S/server-client-tcp/client.py, S/server-client-tcp/readme.md, S/server-client-tcp/server.py
Created a tcp/ip program using python
=> added a client-server tcp program

A/atbash-ciper/README.md, A/atbash-ciper/atbash-cipher.py
This PR introduces the Atbash Cipher, a cipher that replaces each letter with its mirror image in the alphabet. For example, 'A' becomes 'Z', 'B' becomes 'Y', and so on.
=> Added A/atbash-cipher and README

C/color-morph/README.md, C/color-morph/colorMorph.py
Introducing ColorMorph, A Python tool for seamless color conversion between HEX, RGB, and HSL formats. Simplify your color manipulation tasks with this lightweight and versatile tool. 
I invite the project maintainer to review and consider merging this contribution, which aligns with the spirit of Hacktoberfest 2023 and enhances the offerings in our repository
=> add: color-morph color conversion tool

B/Binary search/binary_search.py
This pull request introduces a new binary search algorithm to the project. The binary search function is designed to efficiently locate elements in a sorted array.
The binary search algorithm has a time complexity of **O(log n),** making it a suitable choice for large datasets. The implementation ensures that the array is sorted before performing the search, as the algorithm requires a sorted array for accurate results.
=> Added binary search program

B/basic-blockchain/basic-blockchain.py, README.md
Added a basic blockchain skeleton with essential features and an api to interact with it
=> Add basic blockchain and update README

T/turtle-crossing/car_manager.py, T/turtle-crossing/main.py, T/turtle-crossing/player.py, T/turtle-crossing/scoreboard.py
Added turtle-crossing game written in python, please find below the snapshot for reference.
=> Added turtle-crossing game written in python

B/button-in-pygame/README.md
This pull request adds a README.md file to the `buttons-in-pygame` directory. The README file provides documentation and usage instructions for the `buttons_pygame.py` script, which creates a simple GUI with buttons using the Pygame library.
- Created a new README.md file.
- Provided information about the prerequisites for running the program.
- Included instructions on how to run the program.
- Explained the usage of the program and how to customize the buttons.
=> Added a README.md file

R/rock paper scissors/README.md, R/rock paper scissors/main.py
CODE: 
- Optimized the Rock Paper Scissors code and added more interesting hand emojis for player engagement. 
- Made the game more interesting by adding rounds so that the players can play for a longer time.
- Made the code more clear.
- Made the game more user-friendly.
README:
-  Updated Readme file according to the changes
-  Made it more readable to the users
-  Made it more cleaner
=> Improvised Rock Paper Scissors. Pull Req for Hacktoberfest.

S/splitwise/CalculationService.py, S/splitwise/CalculationServiceImp.py, S/splitwise/Expense.py, S/splitwise/ExpenseController.py, S/splitwise/README.md, S/splitwise/SplitwiseDriver.py, S/splitwise/User.py, S/splitwise/UserController.py
This is basic implementation attempt for the common machine-coding interview problem "SplitWise" in python.
The solution follows SOLID principles along with OOPs concepts.
=> SplitWise machine-coding implementation in python

Q/Quiz-test.py
Rather simple/basic quizzing app that also has a skipping functionality. Basically anki cards but through your console
=> Added a simple customizable quizzing app

S/snake-game/food.py, S/snake-game/main.py, S/snake-game/scoreboard.py, S/snake-game/snake.py
Added snake game written in python, this project is beginner friendly.
=> Added snake game written in python

V/voice-assistant/Readme.md, V/voice-assistant/VoiceAssistant.py
This is a Python-based voice assistant that can perform various tasks, such as playing songs on YouTube, telling system time and date, and providing information about a topic from Wikipedia. The voice assistant uses popular Python packages like `speech_recognition`, `pyttsx3`, and `wikipedia`.
- Speech recognition for voice commands
- Text-to-speech (TTS) capabilities for providing responses
- Integration with YouTube for playing songs
- Wikipedia integration for information retrieval
- System time and date retrieval
=> Added voice assistant project under Directory V

B/BMI_Calculator.py
This commit adds a Python script for a BMI calculator with a simple Tkinter-based graphical user interface. Users can input their height and weight in meters and kilograms, respectively.
=> Add BMI calculator with GUI

H/hackernews/README.md, H/hackernews/main.py, H/hackernews/requirements.txt
=> Hackernews  Email Newsletter

A/adress book/adressbook.py, A/adress book/readme.md, A/alarm clock/alarmclock.py, A/alarm clock/readme.md, B/battleship game/battleship.py, B/battleship game/readme.md, M/magic 8 ball/magic8ball.py, M/magic 8 ball/readme.md
I implemented Alarm Clock using Python. I also added a read me file explaining the code. Hoping to get the PR merged and getting the Hacktoberfest and hacktoberfest- accepted badge
=> alarm clock

P/Prison management system/PMS code.py, P/Prison management system/readme.md
I implemented Prison management system using python. i also added a readme explaining the code. Hoping to get the PR merged and getting the hacktoberfest and hacktoberfest-accepted badge.
=> Added Prison management system

B/Swap Two Elements in a List
Python Program to Swap Two Elements in a List
=> Create Swap Two Elements in a List

whatsapp boot in python
A WhatsApp bot is application software that is able to carry on communication with humans in a spoken or written manner. And today we are going to learn how we can create a WhatsApp bot using python. First, let’s see the requirements for building the WhatsApp bot using python language.
=> Create building whatsapp boot in python

W/Wikipedia bot/README.md, W/Wikipedia bot/Wikipedia_bot.py
Hi there! I've created a simple Wikipedia surfing bot. It takes input from the user to browse articles on a specific topic and returns a one-line summary of all the articles and the URL. I saw that there is a similar project, but, it only returns the content of a couple hard-coded articles. Please merge this commit!
=> Create Wikipedia bot(not a duplicate)

R/Real time translator/README.md, R/Real time translator/real_time_translator.py
Hi there! I've created a program that uses speech recognition to translate the speech spoken by a user. It can translate speech from English to any other language the user wants. I have documented the code. Thank you!
=> Create real-time speech translator

M/Message-Hiding-in-Image/README.md, M/Message-Hiding-in-Image/project.py, new.cpp, test/test.py
I have made a code for encrypting message in an image.
I hope you consider this as a hacktober fest contribution and give me hacktober fest badges.
=> Message Hiding in an image

D/Dijkstra's Algorithm/dijkstra.py, D/Dijkstra's Algorithm/readme.md, text.py
I implemented Dijkstra algorithm using python. io also added a readme explaining the code. Hoping to get the PR merged and getting the hacktoberfest and hacktoberfest-accepted badge.
=> Added Dijkstra's Algorithmn

S/Split a list into nonprime & prime/code.py
- Created clear comments for the splitting prime and non prime numbers code.
- Also formatted the whole code for ease of understanding for the users
- This pull request is for Hacktoberfest but as a developer, I thrive to contribute more to open source
=> Added Documentation and Formatting.py

E/encrypt-message-based-on-confidentiality/README.md, E/encrypt-message-based-on-confidentiality/encryption_app.py
* brief intro
This is a Python project that allows users to encrypt messages with different levels of confidentiality using a variety of encryption techniques and hashing algorithms.
adding Hacktoberfest accepted label would be much appreciated.
=> Message encryption with cryptographic hashing algorithm
